name: tests

on: [push]

jobs:
  lsp-tests:
    name: LSP tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java 12
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Setup go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: Install gauge on linux
        run: |
          git clone https://github.com/getgauge/gauge
          cd gauge
          go run build/make.go --verbose
          go run build/make.go --install --prefix=/tmp/
          echo "::add-path::/tmp/bin"

      - name: Install Gauge Java plugin from source
        run: |
          ./build.sh forceinstall

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Prep gauge-js
        run: |
          git clone https://github.com/getgauge/gauge-js.git
          cd gauge-js
          npm install
        shell: bash

      - name: Install gauge-js
        run: |
          cd gauge-js
          npm run installPlugin

      - name: Prep LSP tests
        run: |
          git clone https://github.com/getgauge/gauge-lsp-tests
          cd gauge-lsp-tests
          npm install
          gauge install
          gauge -v

      - name: Run LSP tests
        shell: bash
        run: |
          cd gauge-lsp-tests
          gauge run specifications --tags="!knownIssue & (actions_on_project_load | actions_on_file_edit)" --env=java-wd

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: lsp-logs
          path: gauge-lsp-tests/logs
